### PR TITLE
Rework ABF1 conversion

### PR DESCRIPTION
**Pull request by t-b**
The commandline tool abf_to_nwb.py learned having options.

The ABF1Converter was overhauled to meet the following goals:
- default to convert all channels, but allow to convert only a single
channel for stimulus and acquisition
- Uses a more descriptive version string for the device
- Creates compressed datasets for the data
- Has a dedicated way to create HTML files with the ABF metadata
- The code got cleaned up at various places

The code was also adapted to not pass the unit parameter to the
pynwb.PatchClampSeries classes anymore. This is not supported anymore
with the current pynwb version.

With this PR and using the latest pyabf version from https://github.com/swharden/pyABF/pull/93 I've converted the example file via
```
./abf_to_nwb.py data/abf1 --overwrite --acquisitionChannelName Iclamp --stimulusChannelName Current_in
```
to [19122043.zip](https://github.com/youngseok-seo/NWB/files/3937382/19122043.zip).

### CODE REVIEW

**Comment by youngseok-seo** [comment]
Thank you for the edits! 

I tried running the code, but failed due to my pyabf not having the changes you made. It seems that they were not merged to the latest version on pip yet. Is there a way for me to be able to get access to your updates?

**Comment by t-b** [comment]
@youngseok-seo You can clone the repo `https://github.com/t-b/pyABF`, checkout the branch `abfv1-fixes` and `pip install -e .` it. In that way you get pyABF with my fixes.

**Comment by youngseok-seo** [comment]
Hello @t-b,

I was able to successfully convert a set of files including the sample file (19122043.abf) included in this repository. 

However, I ran into some errors while attempting to convert a few other files I had. 

The following error resulted from a voltage clamp abf file. The updates to pyABF seems to retrieve the clamp mode, but shows voltage clamp mode as mode '2'. As it was previously understood from other files that voltage clamp is encoded as '0' (and current clamp as '1'), the error checks implemented to catch any other modes were triggered. Would something as simple as accepting both '0' and '2' as voltage clamp solve the problem?

image

I also received this error in attempting to convert a current clamp file. It seems to have originated from pyABF. I removed the optional arguments for channel names, but pyABF seems to be unable to find a channel. Would files like these require individual inspection to pass in the specific channel names?

image

**Comment by t-b** [comment]
@youngseok-seo Can you post both abf files? Are you using pyabf 2.2.0?

**Comment by youngseok-seo** [comment]
@t-b Sorry about that, the abf files can be found here: https://www.dropbox.com/sh/ao3h3fik1p8gpz5/AABLsI0avyUhVTMe4Jrx-9PRa?dl=0 

Let me know if you have trouble accessing them.

The error messages I posted above were from pyabf 2.1.10. 
I also tried after upgrading to version 2.2.0, but got the same errors for both files. In addition, I received errors in converting `19122043.abf` found in `data/abf1`:

image

Does pyabf v2.2.0 include your fixes that work with the converter?

**Comment by t-b** [comment]
@youngseok-seo Yes pyabf 2.2.0 does incude my fixes. I'll take a look and I already downloaded the files.

**Pull request merged**
